export interface Product {
  id: string;
  slug: string;
  num: string;
  title: string;
  subtitle: string;
  tag: string;
  accent: string;
  accentDim: string;    // accent at 15% opacity for backgrounds
  pages: number;
  chapters: number;
  extras: string;       // "14 prompt templates" etc.
  price: number;        // suggested price
  pdfFilename: string;  // filename in Vercel Blob
  blobKey?: string;     // set after upload-pdfs script runs
  who: string;          // "This guide is for..."
  promise: string;      // one-line transformation promise
  chapters_list: { title: string; description: string }[];
  benefits: string[];
  quote: { text: string; author: string };
  faq: { q: string; a: string }[];
}

export const PRODUCTS: Product[] = [
  {
    id: 'ai-playbook',
    slug: 'ai-playbook',
    num: '01',
    title: "The Non-Techie's AI Playbook",
    subtitle: "Master AI tools for your profession — no coding, no jargon.",
    tag: 'AI · Productivity',
    accent: '#E8A020',
    accentDim: 'rgba(232,160,32,0.12)',
    pages: 92,
    chapters: 12,
    extras: '14 ready-to-use prompt templates',
    price: 27,
    pdfFilename: '01-ai-playbook.pdf',
    who: 'Coaches, real estate agents, teachers, marketers, consultants, and small business owners who want to save 10+ hours a week with AI — without touching a line of code.',
    promise: 'Walk away with a personalized AI workflow that saves you 10+ hours per week — implemented, not just understood.',
    chapters_list: [
      { title: 'Why AI Is Different This Time', description: 'The shift that matters and what it means for your career right now.' },
      { title: 'Your AI Audit', description: 'Find the 3 tasks in your current workflow where AI creates immediate leverage.' },
      { title: 'ChatGPT / Claude 101', description: 'The mental model that makes every AI tool instantly easier to use.' },
      { title: 'Prompt Engineering for Non-Techies', description: '5 prompt structures that get professional-grade results every time.' },
      { title: 'AI for Writing & Communication', description: 'Emails, reports, proposals — done in minutes, not hours.' },
      { title: 'AI for Research & Synthesis', description: 'Get expert-level summaries of any topic in under 10 minutes.' },
      { title: 'AI for Client-Facing Work', description: 'Presentations, pitches, and content your clients will notice.' },
      { title: 'AI Workflows by Profession', description: 'Specific playbooks for 8 professions: coach, realtor, teacher, marketer, consultant, VA, HR, finance.' },
      { title: 'Automation Without Code', description: 'Zapier + Make + AI = your personal assistant that never sleeps.' },
      { title: 'The Privacy & Ethics Guardrails', description: 'What to share, what to protect, and how to stay compliant.' },
      { title: 'Building Your Personal AI Stack', description: 'Free tools vs. paid — what actually earns its price.' },
      { title: 'Your 30-Day AI Integration Plan', description: 'Week-by-week rollout so AI becomes habit, not experiment.' },
    ],
    benefits: [
      'Save 10+ hours per week starting in week one',
      '14 fill-in-the-blank prompt templates for your exact profession',
      'Specific AI playbooks for 8 different professions',
      'No coding, no technical background required',
      'Step-by-step 30-day integration plan',
      'Free tools emphasized — no expensive subscriptions needed',
    ],
    quote: {
      text: "I saved 12 hours in my first week. The chapter on AI for client proposals alone was worth 10x the price.",
      author: "Marketing consultant, Austin TX",
    },
    faq: [
      { q: 'Do I need any technical background?', a: 'Zero. This guide was written specifically for non-technical professionals. If you can use email, you can use AI.' },
      { q: 'Which AI tools does it cover?', a: 'ChatGPT, Claude, Gemini, Perplexity, and several specialized tools. The principles work across all of them.' },
      { q: 'Is this out of date already?', a: 'The core frameworks and prompting techniques are model-agnostic and will stay useful as tools evolve. Specific tool UIs may change, but the mental models won\'t.' },
      { q: 'What format is it in?', a: 'PDF — 92 pages, professionally designed, printable. Instant download after purchase.' },
    ],
  },
  {
    id: 'freelancer-finance',
    slug: 'freelancer-finance',
    num: '02',
    title: "The Freelancer's Money System",
    subtitle: "Taxes, savings, and retirement for gig workers with irregular income.",
    tag: 'Finance · Freelance',
    accent: '#34C97A',
    accentDim: 'rgba(52,201,122,0.12)',
    pages: 88,
    chapters: 10,
    extras: '6 financial worksheets + tax calculator template',
    price: 27,
    pdfFilename: '02-freelancer-money-system.pdf',
    who: 'Freelancers, independent contractors, consultants, and gig workers who are tired of tax surprises, feast-or-famine stress, and zero retirement savings.',
    promise: 'Build a self-sustaining money system that handles irregular income, quarterly taxes, and retirement — on autopilot.',
    chapters_list: [
      { title: 'The Freelancer Financial Reality Check', description: 'Why W-2 money advice doesn\'t work for you — and what does.' },
      { title: 'The 4-Account Money System', description: 'Operating, taxes, savings, and emergency: the exact split percentages.' },
      { title: 'Quarterly Taxes Demystified', description: 'When to pay, how much, and the tool that makes it painless.' },
      { title: 'Deductions Most Freelancers Miss', description: 'Home office, equipment, software, health insurance — your real tax bill is lower than you think.' },
      { title: 'Pricing for Profit', description: 'How to calculate your true hourly rate and never underprice again.' },
      { title: 'Feast-or-Famine Smoothing', description: 'The buffer strategy that eliminates financial anxiety across slow months.' },
      { title: 'Retirement Without an Employer', description: 'SEP-IRA vs. Solo 401k vs. Roth IRA — which is right for your income level.' },
      { title: 'Health Insurance Solutions', description: 'ACA marketplace, freelancer associations, and spouse plan strategy.' },
      { title: 'Contracts & Getting Paid', description: 'How to write invoices, chase payments, and protect yourself legally.' },
      { title: 'Your Annual Financial Review', description: 'The 2-hour year-end process that sets up your next 12 months.' },
    ],
    benefits: [
      'The exact 4-account split to handle any income level',
      '6 financial worksheets including a quarterly tax calculator',
      'Deduction checklist that most freelancers overlook',
      'Feast-or-famine smoothing strategy',
      'Retirement options explained for self-employed income',
      'Payment protection and contract essentials',
    ],
    quote: {
      text: "I had no idea I was missing $4,200 in deductions. First month after reading this, I fixed my tax setup and felt like I got a raise.",
      author: "UX designer, remote",
    },
    faq: [
      { q: 'Is this US-specific?', a: 'Primarily written for US freelancers (SE tax, quarterly payments, IRS). Some concepts apply globally, but tax specifics are US-focused.' },
      { q: 'Do I need an accountant after reading this?', a: 'For complex situations, yes. This guide helps you understand your finances so you can work with an accountant more efficiently — or handle basics yourself.' },
      { q: 'What income level is this for?', a: 'Written for freelancers earning $30k–$200k/year. Strategies apply to most income levels in that range.' },
      { q: 'What format is it in?', a: 'PDF — 88 pages + 6 worksheets in a separate file. Instant download after purchase.' },
    ],
  },
  {
    id: 'small-biz-ai',
    slug: 'small-biz-ai',
    num: '03',
    title: "Small Business AI Toolkit",
    subtitle: "Automate operations and outcompete larger rivals — no IT department needed.",
    tag: 'Business · AI',
    accent: '#5B8DEE',
    accentDim: 'rgba(91,141,238,0.12)',
    pages: 96,
    chapters: 13,
    extras: '8 automation templates + vendor comparison matrix',
    price: 37,
    pdfFilename: '03-small-business-ai-toolkit.pdf',
    who: 'Small business owners with 1–20 employees who want to automate repetitive work, improve customer experience, and compete with larger competitors without a big tech budget.',
    promise: 'Automate 15+ hours of weekly busywork and create a customer experience that outperforms businesses 10x your size.',
    chapters_list: [
      { title: 'The Small Business AI Opportunity', description: 'Why small businesses can actually move faster than enterprises with AI.' },
      { title: 'Your Business Automation Audit', description: 'Identify the 5 highest-leverage automation opportunities in your current operation.' },
      { title: 'AI for Customer Service', description: 'Chatbots, FAQ automation, and email handling that works 24/7.' },
      { title: 'AI for Marketing & Social Media', description: 'Content calendars, captions, ads, and emails — all drafted by AI.' },
      { title: 'AI for Operations & Admin', description: 'Scheduling, invoicing, data entry, and document creation automation.' },
      { title: 'AI for Sales & Follow-up', description: 'Lead qualification, proposal writing, and automated follow-up sequences.' },
      { title: 'AI for Hiring & HR', description: 'Job descriptions, screening questions, onboarding docs — at scale.' },
      { title: 'No-Code Automation Stacks', description: 'Zapier, Make, and AI — building workflows without writing a line of code.' },
      { title: 'Tools by Business Type', description: 'Restaurant, retail, service business, professional services — specific tool recommendations.' },
      { title: 'Cost-Benefit Analysis of AI Tools', description: 'How to evaluate any AI tool with a simple ROI framework.' },
      { title: 'Implementation Roadmap', description: 'What to automate first, second, and third — with timelines.' },
      { title: 'Training Your Team', description: 'Getting buy-in and building AI literacy across your staff.' },
      { title: 'Staying Ahead', description: 'How to monitor AI developments and keep your stack current.' },
    ],
    benefits: [
      'Automate 15+ hours of weekly admin and busywork',
      '8 ready-to-deploy automation workflow templates',
      'AI tool recommendations for 6 business types',
      'No-code tools only — no IT department required',
      'Vendor comparison matrix for all major AI tools',
      'Step-by-step 90-day implementation roadmap',
    ],
    quote: {
      text: "We automated our customer inquiry responses and booking process. I got back 20 hours a week — that's a part-time employee's worth of work.",
      author: "Salon owner, Denver CO",
    },
    faq: [
      { q: 'What size business is this for?', a: 'Written for 1–20 person businesses. Solo operators to small teams — all strategies are sized appropriately.' },
      { q: 'Do I need any technical skills?', a: 'No. Every tool and workflow uses no-code platforms. If you can use a smartphone, you can implement these.' },
      { q: 'What will it cost to implement?', a: 'Most tools have free tiers. We walk through what\'s free vs. paid and give honest cost estimates. Budget of $50–$200/month covers most implementations.' },
      { q: 'What format is it in?', a: 'PDF — 96 pages + 8 automation templates. Instant download after purchase.' },
    ],
  },
  {
    id: 'local-marketing',
    slug: 'local-marketing',
    num: '04',
    title: "Local Business Marketing Playbook 2026",
    subtitle: "Get more customers from your neighborhood — Google, social, and word of mouth.",
    tag: 'Marketing · Local',
    accent: '#E05252',
    accentDim: 'rgba(224,82,82,0.12)',
    pages: 84,
    chapters: 11,
    extras: 'Google Business Profile audit template + 30-day content calendar',
    price: 27,
    pdfFilename: '04-local-marketing-playbook.pdf',
    who: 'Local business owners — restaurants, salons, gyms, retailers, contractors, dentists, and any service business that depends on customers within a specific geographic area.',
    promise: 'Show up first on Google for your local area and turn your neighborhood into a steady stream of new customers.',
    chapters_list: [
      { title: 'How Local Search Actually Works in 2026', description: 'Google\'s algorithm changes and what ranks businesses at the top now.' },
      { title: 'Google Business Profile Mastery', description: 'Complete setup, optimization, and the weekly routine that keeps you ranking.' },
      { title: 'Review Generation Systems', description: 'Ethical, effective ways to get 4-5 star reviews consistently.' },
      { title: 'Local SEO Without a Web Developer', description: 'Citations, keywords, and on-page tweaks that move the needle.' },
      { title: 'Social Media for Local Businesses', description: 'What to post, when, and how to turn followers into foot traffic.' },
      { title: 'Email Marketing for Local', description: 'Build your list, send campaigns, and bring customers back.' },
      { title: 'Paid Ads on a Small Budget', description: 'Google Local Ads, Meta radius targeting — how to spend $10/day effectively.' },
      { title: 'Referral & Partnership Programs', description: 'Systematic word-of-mouth that compounds over time.' },
      { title: 'Seasonal Campaigns', description: 'Holiday, summer, back-to-school — planning your marketing year in advance.' },
      { title: 'Tracking What\'s Working', description: 'Simple analytics setup to know which channels drive real customers.' },
      { title: 'Your 90-Day Local Marketing Plan', description: 'Prioritized action plan with week-by-week milestones.' },
    ],
    benefits: [
      'Dominate local Google search for your business category',
      'Step-by-step Google Business Profile optimization',
      'Review generation system with email/SMS templates',
      '30-day social media content calendar',
      'Paid ads guide for budgets as low as $10/day',
      'Referral program templates ready to deploy',
    ],
    quote: {
      text: "Our Google ranking went from page 3 to position 2 within 6 weeks. Phone calls up 40%. Best $27 I've spent on marketing.",
      author: "Plumbing business owner, Ohio",
    },
    faq: [
      { q: 'Does this work for service-area businesses?', a: 'Yes. There\'s a full section on service-area businesses (contractors, landscapers, mobile services) who don\'t have a storefront.' },
      { q: 'How much budget do I need?', a: 'Many strategies are completely free (Google Business, social, reviews, referrals). Paid ads section covers starting from $10/day.' },
      { q: 'Is this updated for 2026?', a: 'Yes. Written in early 2026 with current Google algorithm factors and platform changes included.' },
      { q: 'What format is it in?', a: 'PDF — 84 pages + Google Business audit template + content calendar. Instant download.' },
    ],
  },
  {
    id: 'remote-jobs',
    slug: 'remote-jobs',
    num: '05',
    title: "Remote Job Blueprint for Non-Techies",
    subtitle: "Land a $60k–$90k remote job without a computer science degree.",
    tag: 'Career · Remote',
    accent: '#9B59B6',
    accentDim: 'rgba(155,89,182,0.12)',
    pages: 90,
    chapters: 12,
    extras: 'Resume template + LinkedIn optimization checklist + 50 remote job boards',
    price: 19,
    pdfFilename: '05-remote-job-blueprint.pdf',
    who: 'People who want to work remotely but believe they\'re "not technical enough" — customer service pros, project managers, teachers, HR specialists, marketers, and anyone in a people-facing role.',
    promise: 'Land your first (or better) remote job within 90 days — without switching careers or getting a computer science degree.',
    chapters_list: [
      { title: 'The Remote Job Market in 2026', description: 'Which roles are exploding, which are contracting, and where the real opportunities are.' },
      { title: 'Non-Technical Roles That Pay $60k+', description: '40+ specific job titles that are remote-friendly, well-paid, and not tech roles.' },
      { title: 'Your Remote-Ready Resume', description: 'The exact format and keywords hiring managers look for in remote candidates.' },
      { title: 'LinkedIn for Remote Job Hunting', description: 'Profile optimization that makes recruiters come to you.' },
      { title: 'Where to Actually Find Remote Jobs', description: '50 curated job boards — including niche boards most people don\'t know about.' },
      { title: 'The Application System', description: 'Volume + quality: how to apply to 15–20 jobs per week without burning out.' },
      { title: 'Acing the Remote Interview', description: 'Home setup, answer frameworks, and the questions that trip candidates up.' },
      { title: 'Salary Negotiation for Remote Roles', description: 'Remote pay is often lower — here\'s how to negotiate it back up.' },
      { title: 'Freelance to Full-Time Remote', description: 'Using freelancing as a bridge to a full-time remote position.' },
      { title: 'Upskilling Fast', description: 'The specific certifications that open doors in 3–6 months (mostly free).' },
      { title: 'Starting Strong Remotely', description: 'How to onboard, build visibility, and get promoted when no one can see you.' },
      { title: 'Your 90-Day Remote Job Plan', description: 'Week-by-week action plan from preparation to signed offer.' },
    ],
    benefits: [
      'List of 40+ high-paying non-technical remote job titles',
      'Resume template optimized for remote hiring',
      '50 remote job boards including hidden gems',
      'LinkedIn optimization checklist',
      'Salary negotiation script for remote roles',
      '90-day week-by-week job search plan',
    ],
    quote: {
      text: "I thought remote work was only for developers. Found a $72k remote customer success role in 11 weeks using this system.",
      author: "Former retail manager, switched to remote",
    },
    faq: [
      { q: 'Do I need a degree?', a: 'No. Most of the roles highlighted don\'t require degrees, and we cover how to position experience over credentials.' },
      { q: 'What if I have no remote experience?', a: 'There\'s a full chapter on how to frame in-person experience as remote-relevant and build your remote track record.' },
      { q: 'Is this for US-based jobs?', a: 'Primarily US and global remote roles. Most boards and strategies apply to English-speaking markets worldwide.' },
      { q: 'What format is it in?', a: 'PDF — 90 pages + resume template + checklist. Instant download.' },
    ],
  },
  {
    id: 'wellness-50',
    slug: 'wellness-50',
    num: '06',
    title: "The 50+ Mobility & Energy System",
    subtitle: "Rebuild your strength, fix your joints, and feel better at 55 than you did at 45.",
    tag: 'Health · Wellness',
    accent: '#27AE60',
    accentDim: 'rgba(39,174,96,0.12)',
    pages: 86,
    chapters: 11,
    extras: '4-week starter program + supplement reference guide',
    price: 27,
    pdfFilename: '06-wellness-50-plus.pdf',
    who: 'Adults 50–70 who feel stiff, low-energy, or are frustrated that the approaches that worked at 40 no longer work — and want evidence-backed strategies that account for how bodies actually change after 50.',
    promise: 'Build sustainable energy, fix nagging joint pain, and move better within 30 days — without extreme diets or punishing workouts.',
    chapters_list: [
      { title: 'How Your Body Changes After 50', description: 'The physiology behind what you\'re experiencing — and why it\'s fixable.' },
      { title: 'The Mobility Foundation', description: '15-minute daily routine that addresses the joints that decline fastest after 50.' },
      { title: 'Strength Training After 50', description: 'Why muscle is the most important health metric — and how to build it safely.' },
      { title: 'Energy at the Cellular Level', description: 'Sleep, mitochondria, and the lifestyle factors that determine your daily energy.' },
      { title: 'Eating for Your Changing Metabolism', description: 'Protein timing, anti-inflammatory foods, and what the research actually says.' },
      { title: 'The Sleep Optimization Blueprint', description: 'Why sleep changes after 50 and the evidence-backed fixes that work.' },
      { title: 'Joint Pain Without Surgery', description: 'The movement and lifestyle approaches that reduce chronic joint pain.' },
      { title: 'Managing the Hormonal Shift', description: 'For men and women — understanding what\'s happening and your options.' },
      { title: 'Brain Health & Cognitive Fitness', description: 'Evidence-backed practices that protect memory and mental sharpness.' },
      { title: 'Stress, Resilience & Recovery', description: 'Why recovery matters more after 50 and how to build it in.' },
      { title: 'Your First 30 Days', description: 'The starter program that builds the habits without overwhelming you.' },
    ],
    benefits: [
      '4-week starter program designed specifically for 50+ physiology',
      'Evidence-backed (not trendy) approach to joint pain',
      'Strength training protocols safe for older adults',
      'Sleep optimization guide for post-50 changes',
      'Supplement reference guide with evidence ratings',
      'Written for real people, not competitive athletes',
    ],
    quote: {
      text: "I've read every \"wellness for seniors\" book. This is the first one that treated me like an adult and gave me real science, not just \"take a walk.\"",
      author: "Retired teacher, 63",
    },
    faq: [
      { q: 'Do I need equipment?', a: 'The mobility and starter programs require no equipment. Strength training sections cover both gym and home options.' },
      { q: 'Is this medically reviewed?', a: 'Written based on current sports medicine and gerontology research. Always consult your doctor before starting a new exercise program, especially with existing conditions.' },
      { q: 'Is this for men or women?', a: 'Both. There\'s a dedicated chapter on hormonal changes for each, and the general programs apply to all genders.' },
      { q: 'What format is it in?', a: 'PDF — 86 pages + 4-week program + supplement guide. Instant download.' },
    ],
  },
  {
    id: 'notion-os',
    slug: 'notion-os',
    num: '07',
    title: "Solopreneur OS in Notion",
    subtitle: "Run your entire one-person business from a single Notion dashboard.",
    tag: 'Productivity · Systems',
    accent: '#E8A020',
    accentDim: 'rgba(232,160,32,0.12)',
    pages: 82,
    chapters: 10,
    extras: 'Duplicate-ready Notion template + client tracker + weekly review system',
    price: 37,
    pdfFilename: '07-solopreneur-notion-os.pdf',
    who: 'Freelancers, consultants, coaches, and creators who are drowning in scattered tools, lost tasks, and client chaos — and want one system that runs everything.',
    promise: 'Replace your scattered tools with one Notion workspace that manages clients, projects, finances, and your week — in under 2 hours of setup.',
    chapters_list: [
      { title: 'Why Most Notion Setups Fail', description: 'The overcomplicated approach that kills productivity — and the simple alternative.' },
      { title: 'The Solopreneur OS Architecture', description: 'The 5-database structure that covers every part of a one-person business.' },
      { title: 'Client Command Center', description: 'Track every client, project, deadline, and deliverable in one view.' },
      { title: 'Project Management Without Overhead', description: 'Task management that actually gets used because it\'s not complex.' },
      { title: 'Financial Dashboard', description: 'Income, expenses, invoices, and annual projection — live and always accurate.' },
      { title: 'Content & Ideas Engine', description: 'Capture, develop, and publish content from one place.' },
      { title: 'The Weekly Operating Rhythm', description: 'A 30-minute weekly review that keeps everything on track.' },
      { title: 'Automating with Notion AI', description: 'Let Notion AI write, summarize, and update your database entries.' },
      { title: 'Connecting to Other Tools', description: 'How to sync with Slack, Google Calendar, Gmail, and your CRM.' },
      { title: 'Scaling the System', description: 'When you hire your first VA or contractor — how to extend the OS.' },
    ],
    benefits: [
      'Complete Notion workspace template (duplicate in one click)',
      'Client tracker with automated status updates',
      'Financial dashboard with income projection',
      '30-minute weekly review system',
      'Notion AI automations set up and explained',
      'Integration guides for 6 popular tools',
    ],
    quote: {
      text: "I cancelled 3 SaaS subscriptions after setting this up. Everything's in one place and I actually use it daily.",
      author: "Brand strategist, 4-year solopreneur",
    },
    faq: [
      { q: 'Do I need a paid Notion plan?', a: 'The core template works on the free Notion plan. Some AI features require Notion AI add-on ($10/month). We note which features need paid plans throughout.' },
      { q: 'I\'ve tried Notion before and gave up. Will this be different?', a: 'Most Notion setups fail because they\'re built for the wrong things. This system is specifically designed for client work, not personal productivity — it\'s simpler and more useful.' },
      { q: 'How long does setup take?', a: 'About 2 hours to fully set up — mostly spent entering your existing clients and projects. The template handles all the structure.' },
      { q: 'What format is it in?', a: 'PDF guide (82 pages) + Notion template link included. The template is duplicable to your workspace instantly.' },
    ],
  },
  {
    id: 'etsy-guide',
    slug: 'etsy-guide',
    num: '08',
    title: "Etsy Digital Product Launch Kit",
    subtitle: "Launch your first digital download shop and make your first $1,000.",
    tag: 'E-Commerce · Etsy',
    accent: '#F39C12',
    accentDim: 'rgba(243,156,18,0.12)',
    pages: 88,
    chapters: 12,
    extras: 'Product listing template + keyword research worksheet + pricing calculator',
    price: 27,
    pdfFilename: '08-etsy-launch-kit.pdf',
    who: 'Designers, artists, teachers, and creators who want to sell digital products on Etsy but don\'t know where to start — or have started but aren\'t making consistent sales.',
    promise: 'Launch a profitable Etsy digital shop and make your first $1,000 within 60 days, even starting from zero.',
    chapters_list: [
      { title: 'Why Digital Products on Etsy in 2026', description: 'The market size, the opportunity, and what\'s actually selling right now.' },
      { title: 'Choosing Your Niche', description: 'The demand-first method for finding products people are actively searching for.' },
      { title: 'What to Sell (Even If You\'re Not an Artist)', description: '20 digital product types that sell consistently — including some that require no design skills.' },
      { title: 'Creating with Canva', description: 'The complete Canva workflow for creating professional digital products fast.' },
      { title: 'Etsy SEO Deep Dive', description: 'How Etsy search works and the exact listing optimization that ranks.' },
      { title: 'Listing Optimization', description: 'Titles, tags, descriptions, and photos that convert browsers to buyers.' },
      { title: 'Pricing for Profit', description: 'The pricing formula that maximizes revenue without killing conversion.' },
      { title: 'Your First 10 Sales', description: 'Etsy Ads, social traffic, and the launch momentum strategy.' },
      { title: 'Scaling to $1k/Month', description: 'More products, better SEO, and the review generation strategy.' },
      { title: 'Customer Service That Creates Raving Fans', description: 'How to handle complaints, requests, and turn customers into repeat buyers.' },
      { title: 'Etsy Stats & Analytics', description: 'What to track, what to ignore, and how to make data-driven decisions.' },
      { title: 'From Side Income to Business', description: 'When and how to scale beyond Etsy with your own shop.' },
    ],
    benefits: [
      '20 proven digital product types with market size data',
      'Complete listing optimization system with keyword research',
      'Canva workflow for non-designers',
      'Pricing calculator worksheet',
      'Launch strategy for first 10 sales',
      'Scaling roadmap to $1k/month',
    ],
    quote: {
      text: "Made my first sale 4 days after opening the shop. Hit $1,200 in month 2. I had no design background — this guide made it possible.",
      author: "Elementary school teacher, now Etsy seller",
    },
    faq: [
      { q: 'Do I need design skills?', a: 'No. There are 8 product types that require no design skills, and the Canva guide covers professional-looking products from scratch.' },
      { q: 'How much does it cost to start?', a: '$0.20 per Etsy listing. You can start for under $5. Canva free tier is sufficient for most products.' },
      { q: 'What are the most profitable digital products right now?', a: 'Printables, Notion templates, spreadsheet templates, educational worksheets, and design assets are all strong in 2026. Covered in detail in Chapter 2–3.' },
      { q: 'What format is it in?', a: 'PDF — 88 pages + listing template + keyword research worksheet + pricing calculator. Instant download.' },
    ],
  },
  {
    id: 'homeowner-guide',
    slug: 'homeowner-guide',
    num: '09',
    title: "New Homeowner Survival Guide",
    subtitle: "Everything you need to know in year one — maintenance, repairs, money, and sanity.",
    tag: 'Home · Finance',
    accent: '#3498DB',
    accentDim: 'rgba(52,152,219,0.12)',
    pages: 80,
    chapters: 10,
    extras: 'Annual maintenance calendar + home repair cost reference + contractor red flags checklist',
    price: 19,
    pdfFilename: '09-homeowner-survival-guide.pdf',
    who: 'First-time homeowners in their first 1–3 years of ownership who feel overwhelmed by maintenance, confused about what requires a pro vs. DIY, and anxious about unexpected costs.',
    promise: 'Build confidence, prevent the most expensive mistakes, and create a system that keeps your home healthy and your finances protected.',
    chapters_list: [
      { title: 'Your First 30 Days', description: 'The checklist every new homeowner should complete in month one.' },
      { title: 'Home Systems 101', description: 'HVAC, plumbing, electrical, and structure — what they are, how they work, when to worry.' },
      { title: 'The Annual Maintenance Calendar', description: 'Month-by-month schedule of what to check, clean, and service.' },
      { title: 'DIY vs. Call a Pro', description: 'The clear framework for deciding what to tackle yourself — and when to pick up the phone.' },
      { title: 'Finding Good Contractors', description: 'Vetting, getting quotes, red flags, and avoiding the scams that target homeowners.' },
      { title: 'Emergency Preparedness', description: 'What to do when the pipe bursts at 2am — with phone numbers and shutoff locations.' },
      { title: 'Home Insurance Deep Dive', description: 'What\'s actually covered, what\'s not, and the coverage gaps most homeowners don\'t know about.' },
      { title: 'Building Your Home Emergency Fund', description: 'The 1% rule and how to build a reserve that prevents financial stress.' },
      { title: 'Home Improvement That Adds Value', description: 'Which upgrades ROI well, which don\'t, and the order to prioritize.' },
      { title: 'Year Two and Beyond', description: 'How to build your home knowledge over time and become a confident owner.' },
    ],
    benefits: [
      'Month-by-month annual maintenance calendar',
      'Contractor vetting guide + red flags checklist',
      'Home repair cost reference guide (avg. prices)',
      'Emergency preparedness checklist',
      'Insurance coverage gap analysis',
      'ROI-ranked home improvement priority list',
    ],
    quote: {
      text: "Bought my first house at 31 and had no idea what I was doing. This guide saved me from at least three expensive mistakes in the first year.",
      author: "New homeowner, Charlotte NC",
    },
    faq: [
      { q: 'Is this region-specific?', a: 'Written for general US homeownership. Maintenance timing is for moderate climates — we note adjustments for cold, hot, and humid climates throughout.' },
      { q: 'Do I need DIY skills?', a: 'No. This guide helps you understand your home, not do your own repairs. DIY vs. pro guidance is about helping you make smart decisions, not become a contractor.' },
      { q: 'Is it useful for condos/townhouses?', a: 'Partially. Exterior and structure sections don\'t apply, but systems, insurance, emergency prep, and financial sections all apply fully.' },
      { q: 'What format is it in?', a: 'PDF — 80 pages + maintenance calendar + cost reference + contractor checklist. Instant download.' },
    ],
  },
  {
    id: 'career-pivot',
    slug: 'career-pivot',
    num: '10',
    title: "Career Pivot Blueprint",
    subtitle: "Switch careers after 35 without starting over, taking a pay cut, or going back to school.",
    tag: 'Career · Growth',
    accent: '#E74C3C',
    accentDim: 'rgba(231,76,60,0.12)',
    pages: 94,
    chapters: 12,
    extras: 'Skills transfer worksheet + pivot timeline template + informational interview script',
    price: 27,
    pdfFilename: '10-career-pivot-blueprint.pdf',
    who: 'Professionals 30–55 who feel stuck, burned out, or threatened by AI automation — and want to move into a more fulfilling, better-compensated career without starting from zero.',
    promise: 'Design and execute a career pivot to a role you\'d actually want — within 12 months, without a pay cut, and without going back to school.',
    chapters_list: [
      { title: 'Why Pivoting After 35 Is Actually an Advantage', description: 'Experience as leverage: why mid-career pivots often outperform starting fresh.' },
      { title: 'Diagnosing Your Situation', description: 'The frameworks for figuring out whether you need a pivot, a promotion, or a reset.' },
      { title: 'Mapping Your Transferable Skills', description: 'The skills you already have that are in demand in completely different industries.' },
      { title: 'Target Career Research', description: 'How to evaluate new careers for growth, pay, remote options, and personal fit.' },
      { title: 'The Adjacent Move Strategy', description: 'Why 2–3 smaller moves beats one giant leap — and how to plan them.' },
      { title: 'Upskilling Without Going Back to School', description: 'Certificates, bootcamps, and self-study paths that are actually worth your time and money.' },
      { title: 'Building Your Bridge Experience', description: 'Freelancing, consulting, and side projects that prove competence in the new field.' },
      { title: 'Personal Brand for Career Pivots', description: 'LinkedIn, portfolio, and online presence that positions you for the new role.' },
      { title: 'The Pivot Job Search', description: 'Applying to roles you\'re not "fully qualified" for — and getting callbacks.' },
      { title: 'Interviewing as a Career Changer', description: 'How to answer "why are you switching?" in a way that\'s compelling, not defensive.' },
      { title: 'Salary Negotiation for Pivoters', description: 'How to avoid the pay cut that most career changers accept unnecessarily.' },
      { title: 'Your 12-Month Pivot Plan', description: 'Month-by-month roadmap from where you are now to signed offer.' },
    ],
    benefits: [
      'Skills transfer worksheet to map what you already have',
      'Adjacent move strategy to avoid starting over',
      'Guide to certificates and courses actually worth your time',
      'Informational interview script (used by 3,000+ pivoters)',
      'Salary negotiation guide for career changers',
      '12-month week-by-week pivot roadmap',
    ],
    quote: {
      text: "Pivoted from 12 years in insurance to UX research. The transferable skills framework was the breakthrough — I had more to offer than I thought.",
      author: "Career changer, now senior UX researcher",
    },
    faq: [
      { q: 'What industries does this cover?', a: 'The frameworks work for any industry pivot. Case studies cover tech, healthcare, education, business services, and creative fields.' },
      { q: 'Will I have to take a pay cut?', a: 'Many pivoters do unnecessarily. There\'s a full chapter on how to avoid this — using your experience as leverage and targeting the right entry points.' },
      { q: 'What if I don\'t know what I want to do?', a: 'Chapter 2 is entirely about career direction-finding. There are 4 diagnostic frameworks to help you identify the right target before you start moving.' },
      { q: 'What format is it in?', a: 'PDF — 94 pages + skills transfer worksheet + pivot timeline + interview script. Instant download.' },
    ],
  },
];

export function getProduct(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getAllSlugs(): string[] {
  return PRODUCTS.map((p) => p.slug);
}
